### ISSUE TITLE
Typo in DDCC onboarding checklist file download

### ISSUE THREAD

**Issue by dchocoboo** [WorldHealthOrganization/smart-trust#13]
Hi Carl,

David here from Singapore.
There is a typo in this page
https://smart.who.int/smart-trust/concepts_onboarding.html

When clicking to download the docx [Letter of Application for DDCC by the Full Onboarding Process](https://smart.who.int/smart-trust/Letter_of_Applicaiton_DDCC.docx) (14.3.3), it leads to 404.

Updated the readme in my PR.

Thank you very much

**Comment by dchocoboo** [comment]
https://github.com/WorldHealthOrganization/smart-trust/pull/12

**Comment by litlfred** [comment]
PR merged. Thanks!
